@baseUrl = http://localhost:5000

### GET all characters
GET {{baseUrl}}/characters
Content-Type: application/json

### GET Character by id
GET {{baseUrl}}/characters/:id
Content-Type: application/json

### GET all artifacts
GET {{baseUrl}}/artifacts
Content-Type: application/json

### GET Artifact by id
GET {{baseUrl}}/artifacts/:id
Content-Type: application/json



### POST new Character
POST {{baseUrl}}/characters
Content-Type: application/json

{
    "name": "Muminek",
    "description": "Dobroduszny, ciekawski i wrażliwy mieszkaniec Doliny Muminków, znany ze swojego optymizmu i gościnności.",
    "species": "Muminek",
    "status": "aktywny",
    "friends": [
      "Ryjek",
      "Włóczykij",
      "Mała Mi",
      "Mama Muminka",
      "Tata Muminka"
    ]
}

### POST new Artifact
POST {{baseUrl}}/artifacts
Content-Type: application/json

{
    "name": "Lśniący Kompas Muminka",
    "description": "Stary, mosiężny kompas, który podobno wskazuje nie tylko kierunek geograficzny, ale także drogę do miejsc, gdzie można odnaleźć spokój. Delikatnie świeci, gdy jego właściciel jest blisko czegoś ważnego.",
    "owner": "Muminek"
}



### PUT Character (unfinshed)
PUT {{baseUrl}}/characters/:id
Content-Type: application/json

{
}

### PUT Artifact (unfinshed)
PUT {{baseUrl}}/artifacts/:id
Content-Type: application/json

{
}



### DELETE Character
DELETE {{baseUrl}}/characters/69cbbd9998e28722fb12458a
Content-Type: application/json

### DELETE Artifact
DELETE {{baseUrl}}/artifacts/:id
Content-Type: application/json